#############################################################################
# Makefile for building: PimThai
# Generated by qmake (2.01a) (Qt 4.8.0) on: Sun Apr 29 00:49:51 2012
# Project:  PimThai.pro
# Template: app
# Command: /Users/jay/Jay/Programming/BlackBerry/Qt/bin/qmake -o Makefile PimThai.pro
#############################################################################

####### Compiler, tools and options

CC            = qcc -Vgcc_ntoarmv7le
CXX           = qcc -Vgcc_ntoarmv7le -lang-c++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/unsupported/blackberry-armv7le-g++ -I. -I../Qt/stage/nto/usr/include/qt4/QtCore -I../Qt/stage/nto/usr/include/qt4/QtGui -I../Qt/stage/nto/usr/include/qt4 -I. -I. -I../Qt/stage/nto/usr/include -I/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/usr/include/freetype2
LINK          = qcc -Vgcc_ntoarmv7le -lang-c++
LFLAGS        = -Wl,-rpath-link,/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/lib -Wl,-rpath-link,/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib -Wl,-O1
LIBS          = $(SUBLIBS)  -L/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/lib -L/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib -L/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4/lib -lQtGui -L/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4/lib -L/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/lib -L/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib -lQtCore -lm 
AR            = ntoarmv7-ar cqs
RANLIB        = ntoarmv7-ranlib
QMAKE         = /Users/jay/Jay/Programming/BlackBerry/Qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = ntoarmv7-strip
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base-qnx.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/qconfig.pri \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_config.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_pre.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/release.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_post.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/warn_on.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/moc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/resources.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/uic.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/yacc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/lex.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		PimThai.pro
QMAKE_TARGET  = PimThai
DESTDIR       = 
TARGET        = PimThai

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PimThai.pro  ../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/unsupported/blackberry-armv7le-g++/qmake.conf ../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/unix.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base-qnx.conf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/qconfig.pri \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_config.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_pre.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/release.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_post.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/warn_on.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/moc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/resources.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/uic.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/yacc.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/lex.prf \
		../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtGui.prl \
		/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtCore.prl
	$(QMAKE) -o Makefile PimThai.pro
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-base.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/g++-unix.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/unix.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/common/qcc-base-qnx.conf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/qconfig.pri:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_functions.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt_config.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_pre.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/release.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/default_post.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/warn_on.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/qt.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/unix/thread.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/moc.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/resources.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/uic.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/yacc.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/lex.prf:
../Qt/stage/nto/armle-v7/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtGui.prl:
/Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile PimThai.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PimThai1.0.0 || $(MKDIR) .tmp/PimThai1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PimThai1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/PimThai1.0.0/ && (cd `dirname .tmp/PimThai1.0.0` && $(TAR) PimThai1.0.0.tar PimThai1.0.0 && $(COMPRESS) PimThai1.0.0.tar) && $(MOVE) `dirname .tmp/PimThai1.0.0`/PimThai1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PimThai1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


PimThai.bar: PimThai
	blackberry-nativepackager -devMode -debugToken debugtoken1.bar -package PimThai.bar -arg -platform -arg blackberry bar-descriptor.xml PimThai -e icon.png icon.png -e /Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4//lib/libQtCore.so.4 lib/libQtCore.so.4 -e /Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4//lib/libQtGui.so.4 lib/libQtGui.so.4 -e /Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4//lib/libQtOpenGL.so.4 lib/libQtOpenGL.so.4 -e /Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4//lib/libQtNetwork.so.4 lib/libQtNetwork.so.4 -e /Users/jay/Jay/Programming/BlackBerry/Qt/stage/nto/armle-v7/usr/lib/qt4//plugins/platforms/libblackberry.so lib/platforms/libblackberry.so

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

